- eu_get_status command: shows statistic at the end

diff --git a/commands/eu_get_status b/commands/eu_get_status
--- a/commands/eu_get_status
+++ b/commands/eu_get_status
@@ -1,13 +1,53 @@
 #!/usr/bin/env bash
 
-# idenitify all status files
+function usage {
+  echo "Usage: $(basename $0) [-h]" 2>&1
+  echo "Prints the status of all experiments and repetitions that are below the current directory."
+  echo "  Options:"
+  echo "   -h Shows this message."
+}
+
+# handle arguments
+while getopts ":h" arg; do
+  case $arg in
+    h) usage ; exit 1 ;;
+    ?) echo "Invalid option: -${OPTARG}."; usage ; exit 2 ;;
+  esac
+done
+# get all arguments are given after the options handled by getopts
+shift $(expr $OPTIND - 1 )
+arguments=($@)
+
+############################################
+
+# save statistics about how many scripts have a certain status
+declare -A statistics
+statistics[todo]=0
+statistics[running]=0
+statistics[finished]=0
+statistics[error]=0
+
+# identify all status files
 files=`find . -name *.status | sort -n`
 
 # go through them
+n_files=0
 for file in $files; do
     # read last line with status
     status=$( tail -n 1 $file )
 
+    # create array, which can be used to split a string based on ' '
+    # use only the first term as status
+    status=($status)
+    status=${status[0]}
+
     # output status
-    echo $file - $status
+    echo "$file - $status"
+
+    ((n_files++))
+    statistics[$status]=$((statistics[$status] + 1))
 done
+
+# print statistics
+echo "total: ${n_files} | todo: ${statistics[todo]} | running: ${statistics[running]} | finished: ${statistics[finished]} | error: ${statistics[error]}"
+
diff --git a/commands/eu_local_inria_get_status b/commands/eu_local_inria_get_status
--- a/commands/eu_local_inria_get_status
+++ b/commands/eu_local_inria_get_status
@@ -1,6 +1,27 @@
 #!/usr/bin/env bash
 
-MACHINE=$EU_PRJ_INRIA_DEFAULT_MACHINE
+function usage {
+  echo "Usage: $(basename $0) [-h] [m MACHINE]" 2>&1
+  echo "Prints the status of all experiments and repetitions that are below the current directory at INRIA."
+  echo "  Options:"
+  echo "   -h           Shows this message."
+  echo "   -m MACHINE   Name of the machine at Inria which is used to query the status. (Default: $EU_PRJ_INRIA_DEFAULT_MACHINE)"
+}
+
+ssh_machine=$EU_PRJ_INRIA_DEFAULT_MACHINE
+
+# handle arguments
+while getopts ":hm:" arg; do
+  case $arg in
+    h) usage ; exit 1 ;;
+    m) ssh_machine=${OPTARG};;
+    ?) echo "Invalid option: -${OPTARG}."; usage ; exit 2 ;;
+  esac
+done
+# get all arguments are given after the options handled by getopts
+shift $(expr $OPTIND - 1 )
+arguments=($@)
+
 
 # path to experiments on the local host
 LOCAL_EXPERIMENTS_DIR=$EU_PRJ_LOCAL_EXPERIMENTS_PATH
@@ -12,4 +33,4 @@ LOCAL_SCRIPT_PATH=`pwd`
 EXTERNAL_SCRIPT_PATH=`echo $LOCAL_SCRIPT_PATH | sed "s+${LOCAL_EXPERIMENTS_DIR}+${EXTERNAL_EXPERIMENTS_DIR}+g"`
 
 # got to the current experiment directory on the target host and start the "run_experiments.sh" script
-ssh $MACHINE "source eu_activate $EU_ACTIVE_PRJ; cd ${EXTERNAL_SCRIPT_PATH};  eu_get_status"
+ssh $ssh_machine "source eu_activate $EU_ACTIVE_PRJ; cd ${EXTERNAL_SCRIPT_PATH};  eu_get_status"
